unidoc/unioffice

README.md

- add link to GO report card
- add examples

meta: update README

---

spreadsheet/format/time.go
spreadsheet/parse.go
spreadsheet/sheet.go
spreadsheet/sheet_test.go

Detect overlapping merged cells and report an error
during validation.

spreadsheet: add validation for merged cells

---

filenames_test.go
mingo.go
optional.go
optional_test.go
xsdany.go
xsdany_test.go

- XSDAny
- filename generation
- optional

test: add more tests for xsdany and optional

---

document/document.go
filenames.go
spreadsheet/compare.go
spreadsheet/sheet_test.go

Unit tests

---

schema/soo/sml/CT_ConditionalFormatting.go
schema/soo/sml/CT_Workbook.go
schema/soo/sml/Workbook.go
xsdany.go

spreadsheet: don't allow extra content on Workbook

---

_examples/document/edit-document/main.go
document/document.go
document/document_test.go
document/footer.go
document/header.go
document/hyperlink.go
document/paragraph.go
document/run.go

- adds a Paragraphs() method on Header/Footer
- reworks remove paragraph logic for document to be consistent
Fixes #116

document: support editing headers/footers

---

_examples/document/hyperlink/main.go
document/bookmark.go
document/hyperlink.go
document/paragraph.go

- support adding bookmarks
- support hyperlinks that reference a bookmark
- update hyperlink example
Fixes #126

document: add support for creating bookmarks

---

document/document.go
document/document_test.go

- enumerate bookmarks
- validate that bookmark names are unique

document: support for enumerating bookmarks

---

common/contenttypes.go
document/document.go

document: when adding an image, ensure content-types exist for it

---

document/runproperties.go

document: support super/sub script on text runs

---

schema/soo/dml/chart/Chart.go
schema/soo/dml/chart/ChartSpace.go
schema/soo/dml/chart/UserShapes.go

Add missing reference to http://schemas.openxmlformats.org/drawingml/2006/main
Fixes #155

schema: fix charts

---

document/paragraph.go

fix paragraph numbering id

---

document/section.go

document: adds a helper method to set section margins

---

presentation/open.go
presentation/presentation.go
presentation/read.go

presentation: fix use-template example

---

document/runproperties.go

document: set east asia font family

---

common/relationships.go
common/relationships_test.go

Continued part of #198 after @JasonFromSpace pointed out
an error with the original fix.

common: handle unordered relationships correctly

---

schema/soo/dml/common.go

This fixes #207 
However, as i mentioned in #207 i assume this isn't "how" it should be fixed, as this seems to be generated code, and the generator may need to be adjusted.
Happy to resubmit, if someone can point me to where the generator is (I did a quick look over the code, but couldn't find the generator).

Added empty struct to avoid nill pointer error

---

document/mailmerge.go

document: look for merge fields in tables

---

color/color.go

Added RGBA constructor.

---

document/document.go
document/document_test.go

Included nested tables in document.Tables() output

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/baliance/gooxml/271)

Update README.md - Announcement regarding rename and import path changes

---

spreadsheet/workbook.go

Fixes #289 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/299)

Fix comment on the `AddSheet`

---

document/footer.go
document/header.go

Fixes #296 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/303)

Add tables loop to `Paragraphs` funcs of `Header` and `Footer`

---

presentation/presentation.go
spreadsheet/workbook.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/335)

watermarks for spreadsheets and presentations

---

codecov.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/342)

Set threshold on testing coverage changes

---

internal/mergesort/mergesort.go
spreadsheet/formula/eval_test.go
spreadsheet/formula/fndatetime.go
spreadsheet/formula/fnfinance.go
spreadsheet/formula/fnindex.go
spreadsheet/formula/fnlogical.go
spreadsheet/formula/fnmathtrig.go
spreadsheet/formula/fntext.go
spreadsheet/formula/functions_test.go
spreadsheet/sheet.go

Duration function was not planned in the list, but it is needed for calculating Mduration, so it is included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/353)

Excel functions part 4

---

spreadsheet/format/format.go
spreadsheet/formula/fntext.go
spreadsheet/formula/functions_test.go
spreadsheet/formula/result.go

Addresses #337 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/354)

Excel function: TEXT

---

spreadsheet/formula/functions_test.go

Resolves https://github.com/unidoc/unioffice/issues/355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/357)

Test cases for SUM and IF

---

spreadsheet/formula/fndatetime.go
spreadsheet/formula/fnfinance.go
spreadsheet/formula/functions_test.go

Addresses #356 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/359)

Financial functions - part 1

---

spreadsheet/formula/fnfinance.go
spreadsheet/formula/fnmathtrig.go
spreadsheet/formula/fntext.go
spreadsheet/formula/functions_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/363)

Test cases for functions for https://github.com/unidoc/unioffice/issues/336

---

_examples/document/doc-custom-properties/main.go
common/customproperties.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/380)

Fixes for being able to compile with playground

---

_examples/document/toc-generation-ole/main.go
document/numbering.go

Addresses #383 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/384)

numbering fix

---

_examples/document/paragraphs_in_table/main.go
document/document.go
document/document_test.go

Issue #385 fix
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/387)

Issue #385 fix

---

document/document.go
document/paragraphproperties.go
document/runproperties.go

Example here will be work after accepting: https://play.unidoc.io/p/e15b73f37ddcfdd9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/391)

paragraph and run properties

---

schema/soo/dml/CT_AnimationElementChoice.go
schema/soo/dml/CT_AnimationGraphicalObjectBuildProperties.go
schema/soo/dml/CT_BackgroundFormatting.go
schema/soo/dml/CT_ColorMRU.go
schema/soo/dml/CT_NonVisualContentPartProperties.go
schema/soo/dml/CT_WholeE2oFormatting.go
schema/soo/dml/EG_Media.go

Generated by new schema-generator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/413)

dml struct names fix

---

xsdany.go

https://github.com/unidoc/unioffice/issues/290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unidoc/unioffice/417)

Fixing UO-23
